/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_jni_JavaTC */

#ifndef _Included_com_common_jni_JavaTC
#define _Included_com_common_jni_JavaTC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_jni_JavaTC
 * Method:    getText
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_common_jni_JavaTC_getText
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
